services:
  # Servicio de la base de datos de MySQL
  db:
    image: mysql:8.2.0
    container_name: chat_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # Servicio de phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: chat_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"

  # Servicio de la base de datos de MongoDB
  mongo:
    image: mongo:latest
    container_name: chat_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo_data:/data/db

  # Servicio de Mongo Express
  mongo-express:
    image: mongo-express
    container_name: chat_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    depends_on:
      - mongo

  # Servicio de la aplicación frontend: React
  frontend:
    image: node:lts-alpine
    container_name: chat_react
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"

  # Servicio de la aplicación backend: Node.js
  backend:
    container_name: chat_node
    image: node:lts-bullseye-slim
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run docker"
    depends_on:
      - db
